### ISSUE TITLE
I can't equip any armor in the Curios slots

### ISSUE THREAD

**Issue by ghost** [apace100/cosmetic-armor#3]
I try to drag armor onto the slot and nothing happens. Even the transparent armor from the transparent armor mod.

**Comment by apace100** [comment]
Are you talking exclusively about modded armor, or vanilla armor too? Because modded armor would have to be made compatible by adding it to the tag for the cosmetic slot, e.g. `cosmetic-armor:cosmetic_boots` should contain all your boot armor items.

In the 1.17 version, modded armor is now automatically compatible with the cosmetic slots.

(Sorry, but I won't spend the effort to update older Minecraft versions)
